### PR TITLE
Add Nachthex class by StregaFlora.

### PR DESCRIPTION
**Pull request by mcglincy**
I also added an id field to Author with the intention of DRYing up some entry-making methods... although I haven't embarked on that great adventure yet.

### CODE REVIEW

**Comment by mcglincy** [comment]
Screen Shot 2021-06-30 at 3 49 48 PM

**Comment by makedatanotlore** [comment]
Looking good, but noticed that equipment includes "0s".I think it's better to simply not include that line 🤔

**Comment by mcglincy** [comment]
> Looking good, but noticed that equipment includes "0s".I think it's better to simply not include that line 🤔

removed!

**Comment by makedatanotlore** [comment]
Nice! Merged

**Pull request merged**
